### ISSUE TITLE
Reuse of code in bayesfam

### ISSUE THREAD

**Issue by sims1253** [Dpananos/dpananos.github.io#2]
Hi,
I'd be interested in using your code from eg. the Generalized Gamma or Shifted Beta Geometric distributions for brms custom families in https://github.com/sims1253/bayesfam but that would require a license on this repo (or at least the stan code) as currently the lack of a specific license means "all rights reserved".
Regardless of the specific attribution requirements of the license you'd choose, I would attribute you and link to the corresponding blog posts (unless you explicitly don't want me to do that of course).

Cheers
Maximilian

**Comment by ghost** [comment]
Sure, I think that's fine.  I'll slap a licence in the post's folder
